### PR TITLE
Standardize on four-column tab indents

### PR DESCRIPTION
**Pull request by cxw42**
Ron, thanks for this module, which I have recently started using!  I was looking at the source and noticed some whitespace inconsistencies.  This commit has no functional changes, and all tests pass.  Thanks for considering this PR!

Modifications:
- Convert the few tab indents into space indents, except in Makefiles
- Add a .editorconfig file to configure supported editors for space indents (except Makefile*) (I am an EditorConfig developer)
- Format recent Changes entries to match the format of earlier entries (four-space indents)
- Word-wrap Changes at 80 columns
- Regenerate Changelog.ini
- Add some common temporary-file patterns to .gitignore

### CODE REVIEW

**Comment by ronsavage** [comment]
Thanx for making this effort.
I'll have to think about your suggestions.
For example why convert tabs to spaces? My policy is that all code should uses tabs set to 4 spaces :-).
I have not heard of an .editorconfig file. Is there some place I an read up on it? My editor is uex (UltraEdit for Linux) and my OS is Debian.
Reformatting Changes is definitely a good idea.
The other ideas are good, too.

**Comment by ronsavage** [comment]
Also, please have a look at [Regexp::Parsertron](https://metacpan.org/release/Regexp-Parsertron).
It is my regexp parser, but does not pretend to be a replacement of Regexp::Assemble. That is, it may simply not be relevant to your use case.

**Comment by cxw42** [comment]
Ron, thanks for the quick reply!  I went with what appeared to be the module's style (I see it's one you inherited).  I am happy to switch to tabs; let me know if you would like me to change this PR accordingly.

EditorConfig is <https://editorconfig.org>.  I am currently the primary maintainer of the Vim plugin, which I think works very nicely :D .

Thanks for the tip on Parsertron --- I'll take a look!

**Comment by ronsavage** [comment]
Hi Chris

Thanx for the link. Good idea actually.

And yes, I'd prefer you to recast your patches per tabs.

---
Ron Savage
savage.net.au 
On 2020-03-30 12:57, Chris White wrote:

> Ron, thanks for the quick reply! I went with what appeared to be the module's style (I see it's one you inherited). I am happy to switch to tabs; let me know if you would like me to change this PR accordingly. 
> 
> EditorConfig is https://editorconfig.org. I am currently the primary maintainer of the Vim plugin, which I think works very nicely :D . 
> 
> Thanks for the tip on Parsertron --- I'll take a look! 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/ronsavage/Regexp-Assemble/pull/8#issuecomment-605742185
[2]

**Comment by ronsavage** [comment]
Hi

Oops. I thought your name was Chris, and sorry if it isn't.

---
Ron Savage
savage.net.au 
On 2020-03-30 12:57, Chris White wrote:

> Ron, thanks for the quick reply! I went with what appeared to be the module's style (I see it's one you inherited). I am happy to switch to tabs; let me know if you would like me to change this PR accordingly. 
> 
> EditorConfig is https://editorconfig.org. I am currently the primary maintainer of the Vim plugin, which I think works very nicely :D . 
> 
> Thanks for the tip on Parsertron --- I'll take a look! 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/ronsavage/Regexp-Assemble/pull/8#issuecomment-605742185
[2]

**Comment by cxw42** [comment]
No worries - Chris is fine :) .  Will do!

**Comment by cxw42** [comment]
@ronsavage Changed to tabs in c47f38e.  Some of the test files have space indents in multiline `q()` strings in order to match the output of `indent()`.

I also update the README to list this repo's URL and note that you have co-maint.

**Pull request merged**
